// Code generated by Gopapageno; DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/giornetta/gopapageno"
	"strings"
)

import (
	"math"
)

var parserPools []*gopapageno.Pool[int64]

func ParserPreallocMem(inputSize int, numThreads int) {
	parserPools = make([]*gopapageno.Pool[int64], numThreads)

	avgCharsPerNumber := float64(2)
	poolSizePerThread := int(math.Ceil((float64(inputSize) / avgCharsPerNumber) / float64(numThreads)))

	for i := 0; i < numThreads; i++ {
		parserPools[i] = gopapageno.NewPool[int64](poolSizePerThread)
	}
}

// Non-terminals
const (
	E_S = gopapageno.TokenEmpty + 1 + iota
	NEW_AXIOM
)

// Terminals
const (
	LPAR = gopapageno.TokenTerm + 1 + iota
	NUMBER
	PLUS
	RPAR
	S
)

func SprintToken[TokenValue any](root *gopapageno.Token) string {
	var sprintRec func(t *gopapageno.Token, sb *strings.Builder, indent string)

	sprintRec = func(t *gopapageno.Token, sb *strings.Builder, indent string) {
		if t == nil {
			return
		}

		sb.WriteString(indent)
		if t.Next == nil {
			sb.WriteString("└── ")
			indent += "    "
		} else {
			sb.WriteString("├── ")
			indent += "|   "
		}

		switch t.Type {
		case E_S:
			sb.WriteString("E_S")
		case NEW_AXIOM:
			sb.WriteString("NEW_AXIOM")
		case gopapageno.TokenEmpty:
			sb.WriteString("Empty")
		case LPAR:
			sb.WriteString("LPAR")
		case NUMBER:
			sb.WriteString("NUMBER")
		case PLUS:
			sb.WriteString("PLUS")
		case RPAR:
			sb.WriteString("RPAR")
		case S:
			sb.WriteString("S")
		case gopapageno.TokenTerm:
			sb.WriteString("Term")
		default:
			sb.WriteString("Unknown")
		}
		if t.Value != nil {
			sb.WriteString(fmt.Sprintf(": %v", *t.Value.(*TokenValue)))
		}
		sb.WriteString("\n")

		sprintRec(t.Child, sb, indent)
		sprintRec(t.Next, sb, indent[:len(indent)-4])
	}

	var sb strings.Builder

	sprintRec(root, &sb, "")

	return sb.String()
}

func NewParser(opts ...gopapageno.ParserOpt) *gopapageno.Parser {
	numTerminals := uint16(6)
	numNonTerminals := uint16(3)

	maxRHSLen := 3
	rules := []gopapageno.Rule{
		{NEW_AXIOM, []gopapageno.TokenType{E_S}, gopapageno.RuleSimple},
		{E_S, []gopapageno.TokenType{E_S, PLUS, E_S}, gopapageno.RuleSimple},
		{E_S, []gopapageno.TokenType{LPAR, E_S, RPAR}, gopapageno.RuleSimple},
		{E_S, []gopapageno.TokenType{NUMBER}, gopapageno.RuleSimple},
		{NEW_AXIOM, []gopapageno.TokenType{S}, gopapageno.RuleSimple},
	}
	compressedRules := []uint16{0, 0, 4, 1, 11, 32769, 24, 32770, 37, 32773, 40, 2, 0, 1, 32771, 16, 0, 0, 1, 1, 21, 1, 1, 0, 0, 0, 1, 1, 29, 0, 0, 1, 32772, 34, 1, 2, 0, 1, 3, 0, 2, 4, 0}

	precMatrix := [][]gopapageno.Precedence{
		{gopapageno.PrecEquals, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEquals, gopapageno.PrecEquals},
		{gopapageno.PrecTakes, gopapageno.PrecEquals, gopapageno.PrecEquals, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEquals},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecAssociative, gopapageno.PrecTakes, gopapageno.PrecEquals},
		{gopapageno.PrecTakes, gopapageno.PrecEquals, gopapageno.PrecEquals, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEquals},
		{gopapageno.PrecTakes, gopapageno.PrecEquals, gopapageno.PrecEquals, gopapageno.PrecEquals, gopapageno.PrecEquals, gopapageno.PrecEquals},
	}
	bitPackedMatrix := []uint64{
		2486599845373371732, 0,
	}

	fn := func(rule uint16, lhs *gopapageno.Token, rhs []*gopapageno.Token, thread int) {
		var ruleType gopapageno.RuleType
		switch rule {
		case 0:
			ruleType = gopapageno.RuleSimple

			NEW_AXIOM0 := lhs
			E_S1 := rhs[0]

			NEW_AXIOM0.Child = E_S1
			NEW_AXIOM0.LastChild = E_S1

			{
				NEW_AXIOM0.Value = E_S1.Value
			}
			_ = E_S1
		case 1:
			ruleType = gopapageno.RuleSimple

			E_S0 := lhs
			E_S1 := rhs[0]
			PLUS2 := rhs[1]
			E_S3 := rhs[2]

			E_S0.Child = E_S1
			E_S1.Next = PLUS2
			PLUS2.Next = E_S3
			E_S0.LastChild = E_S3

			{
				newValue := parserPools[thread].Get()
				*newValue = *E_S1.Value.(*int64) + *E_S3.Value.(*int64)
				E_S0.Value = newValue
			}
			_ = E_S1
			_ = PLUS2
			_ = E_S3
		case 2:
			ruleType = gopapageno.RuleSimple

			E_S0 := lhs
			LPAR1 := rhs[0]
			E_S2 := rhs[1]
			RPAR3 := rhs[2]

			E_S0.Child = LPAR1
			LPAR1.Next = E_S2
			E_S2.Next = RPAR3
			E_S0.LastChild = RPAR3

			{
				E_S0.Value = E_S2.Value
			}
			_ = LPAR1
			_ = E_S2
			_ = RPAR3
		case 3:
			ruleType = gopapageno.RuleSimple

			E_S0 := lhs
			NUMBER1 := rhs[0]

			E_S0.Child = NUMBER1
			E_S0.LastChild = NUMBER1

			{
				E_S0.Value = NUMBER1.Value
			}
			_ = NUMBER1
		case 4:
			ruleType = gopapageno.RuleSimple

			NEW_AXIOM0 := lhs
			S1 := rhs[0]

			NEW_AXIOM0.Child = S1
			NEW_AXIOM0.LastChild = S1

			{
				NEW_AXIOM0.Value = S1.Value
			}
			_ = S1
		}
		_ = ruleType
	}

	return gopapageno.NewParser(
		NewLexer(),
		numTerminals,
		numNonTerminals,
		maxRHSLen,
		rules,
		compressedRules,
		precMatrix,
		bitPackedMatrix,
		fn,
		gopapageno.AOPP,
		opts...)
}
