// Code generated by Gopapageno; DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/giornetta/gopapageno"
	"strings"
)

// Non-terminals
const (
	Array_Elements_Value = gopapageno.TokenEmpty + 1 + iota
	Document
	Elements
	Elements_Object_Value
	Elements_Value
	Members
	Members_Pair
)

// Terminals
const (
	BOOL = gopapageno.TokenTerm + 1 + iota
	COLON
	COMMA
	LCURLY
	LSQUARE
	NULL
	NUMBER
	RCURLY
	RSQUARE
	STRING
)

func SprintToken[ValueType any](root *gopapageno.Token) string {
	var sprintRec func(t *gopapageno.Token, sb *strings.Builder, indent string)

	sprintRec = func(t *gopapageno.Token, sb *strings.Builder, indent string) {
		if t == nil {
			return
		}

		sb.WriteString(indent)
		if t.Next == nil {
			sb.WriteString("└── ")
			indent += "    "
		} else {
			sb.WriteString("├── ")
			indent += "|   "
		}

		switch t.Type {
		case Array_Elements_Value:
			sb.WriteString("Array_Elements_Value")
		case Document:
			sb.WriteString("Document")
		case Elements:
			sb.WriteString("Elements")
		case Elements_Object_Value:
			sb.WriteString("Elements_Object_Value")
		case Elements_Value:
			sb.WriteString("Elements_Value")
		case Members:
			sb.WriteString("Members")
		case Members_Pair:
			sb.WriteString("Members_Pair")
		case gopapageno.TokenEmpty:
			sb.WriteString("Empty")
		case BOOL:
			sb.WriteString("BOOL")
		case COLON:
			sb.WriteString("COLON")
		case COMMA:
			sb.WriteString("COMMA")
		case LCURLY:
			sb.WriteString("LCURLY")
		case LSQUARE:
			sb.WriteString("LSQUARE")
		case NULL:
			sb.WriteString("NULL")
		case NUMBER:
			sb.WriteString("NUMBER")
		case RCURLY:
			sb.WriteString("RCURLY")
		case RSQUARE:
			sb.WriteString("RSQUARE")
		case STRING:
			sb.WriteString("STRING")
		case gopapageno.TokenTerm:
			sb.WriteString("Term")
		default:
			sb.WriteString("Unknown")
		}

		if t.Value != nil {
			if v, ok := any(t.Value).(*ValueType); ok {
				sb.WriteString(fmt.Sprintf(": %v", *v))
			}
		}

		sb.WriteString("\n")

		sprintRec(t.Child, sb, indent)
		sprintRec(t.Next, sb, indent[:len(indent)-4])
	}

	var sb strings.Builder

	sprintRec(root, &sb, "")

	return sb.String()
}

func NewGrammar() *gopapageno.Grammar {
	numTerminals := uint16(11)
	numNonTerminals := uint16(8)

	maxRHSLen := 3
	rules := []gopapageno.Rule{
		{Elements, []gopapageno.TokenType{Array_Elements_Value, COMMA, Array_Elements_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Array_Elements_Value, COMMA, Elements_Object_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Array_Elements_Value, COMMA, Elements_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Elements_Object_Value, COMMA, Array_Elements_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Elements_Object_Value, COMMA, Elements_Object_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Elements_Object_Value, COMMA, Elements_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Elements_Value, COMMA, Array_Elements_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Elements_Value, COMMA, Elements_Object_Value}, gopapageno.RuleCyclic},
		{Elements, []gopapageno.TokenType{Elements_Value, COMMA, Elements_Value}, gopapageno.RuleCyclic},
		{Members, []gopapageno.TokenType{Members_Pair, COMMA, Members_Pair}, gopapageno.RuleCyclic},
		{Elements_Value, []gopapageno.TokenType{BOOL}, gopapageno.RuleSimple},
		{Elements_Object_Value, []gopapageno.TokenType{LCURLY, Members, RCURLY}, gopapageno.RuleSimple},
		{Elements_Object_Value, []gopapageno.TokenType{LCURLY, Members_Pair, RCURLY}, gopapageno.RuleSimple},
		{Elements_Object_Value, []gopapageno.TokenType{LCURLY, RCURLY}, gopapageno.RuleSimple},
		{Array_Elements_Value, []gopapageno.TokenType{LSQUARE, Array_Elements_Value, RSQUARE}, gopapageno.RuleSimple},
		{Array_Elements_Value, []gopapageno.TokenType{LSQUARE, Elements, RSQUARE}, gopapageno.RuleSimple},
		{Array_Elements_Value, []gopapageno.TokenType{LSQUARE, Elements_Object_Value, RSQUARE}, gopapageno.RuleSimple},
		{Array_Elements_Value, []gopapageno.TokenType{LSQUARE, Elements_Value, RSQUARE}, gopapageno.RuleSimple},
		{Array_Elements_Value, []gopapageno.TokenType{LSQUARE, RSQUARE}, gopapageno.RuleSimple},
		{Elements_Value, []gopapageno.TokenType{NULL}, gopapageno.RuleSimple},
		{Elements_Value, []gopapageno.TokenType{NUMBER}, gopapageno.RuleSimple},
		{Elements_Value, []gopapageno.TokenType{STRING}, gopapageno.RuleSimple},
		{Members_Pair, []gopapageno.TokenType{STRING, COLON, Array_Elements_Value}, gopapageno.RuleSimple},
		{Members_Pair, []gopapageno.TokenType{STRING, COLON, Elements_Object_Value}, gopapageno.RuleSimple},
		{Members_Pair, []gopapageno.TokenType{STRING, COLON, Elements_Value}, gopapageno.RuleSimple},
	}
	compressedRules := []uint16{0, 0, 10, 1, 23, 4, 46, 5, 69, 7, 92, 32769, 105, 32772, 108, 32773, 136, 32774, 184, 32775, 187, 32778, 190, 0, 0, 1, 32771, 28, 0, 0, 3, 1, 37, 4, 40, 5, 43, 3, 0, 0, 3, 1, 0, 3, 2, 0, 0, 0, 1, 32771, 51, 0, 0, 3, 1, 60, 4, 63, 5, 66, 3, 3, 0, 3, 4, 0, 3, 5, 0, 0, 0, 1, 32771, 74, 0, 0, 3, 1, 83, 4, 86, 5, 89, 3, 6, 0, 3, 7, 0, 3, 8, 0, 0, 0, 1, 32771, 97, 0, 0, 1, 7, 102, 6, 9, 0, 5, 10, 0, 0, 0, 3, 6, 117, 7, 125, 32776, 133, 0, 0, 1, 32776, 122, 4, 11, 0, 0, 0, 1, 32776, 130, 4, 12, 0, 4, 13, 0, 0, 0, 5, 1, 149, 3, 157, 4, 165, 5, 173, 32777, 181, 0, 0, 1, 32777, 154, 1, 14, 0, 0, 0, 1, 32777, 162, 1, 15, 0, 0, 0, 1, 32777, 170, 1, 16, 0, 0, 0, 1, 32777, 178, 1, 17, 0, 1, 18, 0, 5, 19, 0, 5, 20, 0, 5, 21, 1, 32770, 195, 0, 0, 3, 1, 204, 4, 207, 5, 210, 7, 22, 0, 7, 23, 0, 7, 24, 0}

	maxPrefixLength := 4
	prefixes := [][]gopapageno.TokenType{
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Object_Value, COMMA, Elements_Value, COMMA},
		{Elements_Object_Value, COMMA, Array_Elements_Value, COMMA},
		{Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Elements_Value, COMMA, Elements_Value, COMMA},
		{Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Object_Value, COMMA},
		{Array_Elements_Value, COMMA, Elements_Value, COMMA},
		{Array_Elements_Value, COMMA, Array_Elements_Value, COMMA},
		{Members_Pair, COMMA, Members_Pair, COMMA},
	}
	compressedPrefixes := []uint16{0, 0, 8, 4, 19, 5, 57, 1, 95, 1, 113, 1, 211, 4, 229, 5, 307, 7, 385, 0, 0, 1, 32771, 24, 0, 0, 3, 4, 33, 5, 41, 1, 49, 0, 0, 1, 32771, 38, 3, 0, 0, 0, 0, 1, 32771, 46, 3, 0, 0, 0, 0, 1, 32771, 54, 3, 0, 0, 0, 0, 1, 32771, 62, 0, 0, 3, 4, 71, 5, 79, 1, 87, 0, 0, 1, 32771, 76, 3, 0, 0, 0, 0, 1, 32771, 84, 3, 0, 0, 0, 0, 1, 32771, 92, 3, 0, 0, 0, 0, 1, 32771, 100, 0, 0, 1, 4, 105, 0, 0, 1, 32771, 110, 3, 0, 0, 0, 0, 1, 32771, 118, 0, 0, 9, 5, 139, 4, 147, 1, 155, 5, 163, 1, 171, 4, 179, 5, 187, 1, 195, 1, 203, 0, 0, 1, 32771, 144, 3, 1, 0, 0, 0, 1, 32771, 152, 3, 4, 0, 0, 0, 1, 32771, 160, 3, 1, 0, 0, 0, 1, 32771, 168, 3, 4, 0, 0, 0, 1, 32771, 176, 3, 8, 0, 0, 0, 1, 32771, 184, 3, 8, 0, 0, 0, 1, 32771, 192, 3, 8, 0, 0, 0, 1, 32771, 200, 3, 3, 0, 0, 0, 1, 32771, 208, 3, 4, 0, 0, 0, 1, 32771, 216, 0, 0, 1, 1, 221, 0, 0, 1, 32771, 226, 3, 0, 0, 0, 0, 1, 32771, 234, 0, 0, 7, 4, 251, 5, 259, 1, 267, 1, 275, 1, 283, 4, 291, 5, 299, 0, 0, 1, 32771, 256, 3, 3, 0, 0, 0, 1, 32771, 264, 3, 3, 0, 0, 0, 1, 32771, 272, 3, 1, 0, 0, 0, 1, 32771, 280, 3, 8, 0, 0, 0, 1, 32771, 288, 3, 3, 0, 0, 0, 1, 32771, 296, 3, 8, 0, 0, 0, 1, 32771, 304, 3, 8, 0, 0, 0, 1, 32771, 312, 0, 0, 7, 4, 329, 5, 337, 1, 345, 1, 353, 1, 361, 4, 369, 5, 377, 0, 0, 1, 32771, 334, 3, 3, 0, 0, 0, 1, 32771, 342, 3, 3, 0, 0, 0, 1, 32771, 350, 3, 1, 0, 0, 0, 1, 32771, 358, 3, 8, 0, 0, 0, 1, 32771, 366, 3, 3, 0, 0, 0, 1, 32771, 374, 3, 8, 0, 0, 0, 1, 32771, 382, 3, 8, 0, 0, 0, 1, 32771, 390, 0, 0, 1, 7, 395, 0, 0, 1, 32771, 400, 6, 9, 0}

	precMatrix := [][]gopapageno.Precedence{
		{gopapageno.PrecEquals, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecEmpty, gopapageno.PrecEquals, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecYields, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEquals, gopapageno.PrecEmpty, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecEmpty, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEmpty, gopapageno.PrecEquals, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty},
	}
	bitPackedMatrix := []uint64{
		2691009079795864916, 1536167278698648601, 36635736172136484, 1301856705847434,
	}

	fn := func(ruleDescription uint16, ruleFlags gopapageno.RuleFlags, lhs *gopapageno.Token, rhs []*gopapageno.Token, thread int) {
		switch ruleDescription {
		case 0:
			Elements0 := lhs
			Array_Elements_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Array_Elements_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Array_Elements_Value1
				Array_Elements_Value1.Next = COMMA2
			}

			COMMA2.Next = Array_Elements_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Array_Elements_Value3.Child
				Elements0.LastChild = Array_Elements_Value3.LastChild
			} else {
				COMMA2.Next = Array_Elements_Value3
				Elements0.LastChild = Array_Elements_Value3
			}

			{
			}
			_ = Array_Elements_Value1
			_ = COMMA2
			_ = Array_Elements_Value3
		case 1:
			Elements0 := lhs
			Array_Elements_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Elements_Object_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Array_Elements_Value1
				Array_Elements_Value1.Next = COMMA2
			}

			COMMA2.Next = Elements_Object_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Elements_Object_Value3.Child
				Elements0.LastChild = Elements_Object_Value3.LastChild
			} else {
				COMMA2.Next = Elements_Object_Value3
				Elements0.LastChild = Elements_Object_Value3
			}

			{
			}
			_ = Array_Elements_Value1
			_ = COMMA2
			_ = Elements_Object_Value3
		case 2:
			Elements0 := lhs
			Array_Elements_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Elements_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Array_Elements_Value1
				Array_Elements_Value1.Next = COMMA2
			}

			COMMA2.Next = Elements_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Elements_Value3.Child
				Elements0.LastChild = Elements_Value3.LastChild
			} else {
				COMMA2.Next = Elements_Value3
				Elements0.LastChild = Elements_Value3
			}

			{
			}
			_ = Array_Elements_Value1
			_ = COMMA2
			_ = Elements_Value3
		case 3:
			Elements0 := lhs
			Elements_Object_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Array_Elements_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Elements_Object_Value1
				Elements_Object_Value1.Next = COMMA2
			}

			COMMA2.Next = Array_Elements_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Array_Elements_Value3.Child
				Elements0.LastChild = Array_Elements_Value3.LastChild
			} else {
				COMMA2.Next = Array_Elements_Value3
				Elements0.LastChild = Array_Elements_Value3
			}

			{
			}
			_ = Elements_Object_Value1
			_ = COMMA2
			_ = Array_Elements_Value3
		case 4:
			Elements0 := lhs
			Elements_Object_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Elements_Object_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Elements_Object_Value1
				Elements_Object_Value1.Next = COMMA2
			}

			COMMA2.Next = Elements_Object_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Elements_Object_Value3.Child
				Elements0.LastChild = Elements_Object_Value3.LastChild
			} else {
				COMMA2.Next = Elements_Object_Value3
				Elements0.LastChild = Elements_Object_Value3
			}

			{
			}
			_ = Elements_Object_Value1
			_ = COMMA2
			_ = Elements_Object_Value3
		case 5:
			Elements0 := lhs
			Elements_Object_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Elements_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Elements_Object_Value1
				Elements_Object_Value1.Next = COMMA2
			}

			COMMA2.Next = Elements_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Elements_Value3.Child
				Elements0.LastChild = Elements_Value3.LastChild
			} else {
				COMMA2.Next = Elements_Value3
				Elements0.LastChild = Elements_Value3
			}

			{
			}
			_ = Elements_Object_Value1
			_ = COMMA2
			_ = Elements_Value3
		case 6:
			Elements0 := lhs
			Elements_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Array_Elements_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Elements_Value1
				Elements_Value1.Next = COMMA2
			}

			COMMA2.Next = Array_Elements_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Array_Elements_Value3.Child
				Elements0.LastChild = Array_Elements_Value3.LastChild
			} else {
				COMMA2.Next = Array_Elements_Value3
				Elements0.LastChild = Array_Elements_Value3
			}

			{
			}
			_ = Elements_Value1
			_ = COMMA2
			_ = Array_Elements_Value3
		case 7:
			Elements0 := lhs
			Elements_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Elements_Object_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Elements_Value1
				Elements_Value1.Next = COMMA2
			}

			COMMA2.Next = Elements_Object_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Elements_Object_Value3.Child
				Elements0.LastChild = Elements_Object_Value3.LastChild
			} else {
				COMMA2.Next = Elements_Object_Value3
				Elements0.LastChild = Elements_Object_Value3
			}

			{
			}
			_ = Elements_Value1
			_ = COMMA2
			_ = Elements_Object_Value3
		case 8:
			Elements0 := lhs
			Elements_Value1 := rhs[0]
			COMMA2 := rhs[1]
			Elements_Value3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Elements0.LastChild.Next = COMMA2
			} else {
				Elements0.Child = Elements_Value1
				Elements_Value1.Next = COMMA2
			}

			COMMA2.Next = Elements_Value3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Elements_Value3.Child
				Elements0.LastChild = Elements_Value3.LastChild
			} else {
				COMMA2.Next = Elements_Value3
				Elements0.LastChild = Elements_Value3
			}

			{
			}
			_ = Elements_Value1
			_ = COMMA2
			_ = Elements_Value3
		case 9:
			Members0 := lhs
			Members_Pair1 := rhs[0]
			COMMA2 := rhs[1]
			Members_Pair3 := rhs[2]

			if ruleFlags.Has(gopapageno.RuleAppend) {
				Members0.LastChild.Next = COMMA2
			} else {
				Members0.Child = Members_Pair1
				Members_Pair1.Next = COMMA2
			}

			COMMA2.Next = Members_Pair3

			if ruleFlags.Has(gopapageno.RuleCombine) {
				COMMA2.Next = Members_Pair3.Child
				Members0.LastChild = Members_Pair3.LastChild
			} else {
				COMMA2.Next = Members_Pair3
				Members0.LastChild = Members_Pair3
			}

			{
			}
			_ = Members_Pair1
			_ = COMMA2
			_ = Members_Pair3
		case 10:
			Elements_Value0 := lhs
			BOOL1 := rhs[0]

			Elements_Value0.Child = BOOL1
			Elements_Value0.LastChild = BOOL1

			{
			}
			_ = BOOL1
		case 11:
			Elements_Object_Value0 := lhs
			LCURLY1 := rhs[0]
			Members2 := rhs[1]
			RCURLY3 := rhs[2]

			Elements_Object_Value0.Child = LCURLY1
			LCURLY1.Next = Members2
			Members2.Next = RCURLY3
			Elements_Object_Value0.LastChild = RCURLY3

			{
			}
			_ = LCURLY1
			_ = Members2
			_ = RCURLY3
		case 12:
			Elements_Object_Value0 := lhs
			LCURLY1 := rhs[0]
			Members_Pair2 := rhs[1]
			RCURLY3 := rhs[2]

			Elements_Object_Value0.Child = LCURLY1
			LCURLY1.Next = Members_Pair2
			Members_Pair2.Next = RCURLY3
			Elements_Object_Value0.LastChild = RCURLY3

			{
			}
			_ = LCURLY1
			_ = Members_Pair2
			_ = RCURLY3
		case 13:
			Elements_Object_Value0 := lhs
			LCURLY1 := rhs[0]
			RCURLY2 := rhs[1]

			Elements_Object_Value0.Child = LCURLY1
			LCURLY1.Next = RCURLY2
			Elements_Object_Value0.LastChild = RCURLY2

			{
			}
			_ = LCURLY1
			_ = RCURLY2
		case 14:
			Array_Elements_Value0 := lhs
			LSQUARE1 := rhs[0]
			Array_Elements_Value2 := rhs[1]
			RSQUARE3 := rhs[2]

			Array_Elements_Value0.Child = LSQUARE1
			LSQUARE1.Next = Array_Elements_Value2
			Array_Elements_Value2.Next = RSQUARE3
			Array_Elements_Value0.LastChild = RSQUARE3

			{
			}
			_ = LSQUARE1
			_ = Array_Elements_Value2
			_ = RSQUARE3
		case 15:
			Array_Elements_Value0 := lhs
			LSQUARE1 := rhs[0]
			Elements2 := rhs[1]
			RSQUARE3 := rhs[2]

			Array_Elements_Value0.Child = LSQUARE1
			LSQUARE1.Next = Elements2
			Elements2.Next = RSQUARE3
			Array_Elements_Value0.LastChild = RSQUARE3

			{
			}
			_ = LSQUARE1
			_ = Elements2
			_ = RSQUARE3
		case 16:
			Array_Elements_Value0 := lhs
			LSQUARE1 := rhs[0]
			Elements_Object_Value2 := rhs[1]
			RSQUARE3 := rhs[2]

			Array_Elements_Value0.Child = LSQUARE1
			LSQUARE1.Next = Elements_Object_Value2
			Elements_Object_Value2.Next = RSQUARE3
			Array_Elements_Value0.LastChild = RSQUARE3

			{
			}
			_ = LSQUARE1
			_ = Elements_Object_Value2
			_ = RSQUARE3
		case 17:
			Array_Elements_Value0 := lhs
			LSQUARE1 := rhs[0]
			Elements_Value2 := rhs[1]
			RSQUARE3 := rhs[2]

			Array_Elements_Value0.Child = LSQUARE1
			LSQUARE1.Next = Elements_Value2
			Elements_Value2.Next = RSQUARE3
			Array_Elements_Value0.LastChild = RSQUARE3

			{
			}
			_ = LSQUARE1
			_ = Elements_Value2
			_ = RSQUARE3
		case 18:
			Array_Elements_Value0 := lhs
			LSQUARE1 := rhs[0]
			RSQUARE2 := rhs[1]

			Array_Elements_Value0.Child = LSQUARE1
			LSQUARE1.Next = RSQUARE2
			Array_Elements_Value0.LastChild = RSQUARE2

			{
			}
			_ = LSQUARE1
			_ = RSQUARE2
		case 19:
			Elements_Value0 := lhs
			NULL1 := rhs[0]

			Elements_Value0.Child = NULL1
			Elements_Value0.LastChild = NULL1

			{
			}
			_ = NULL1
		case 20:
			Elements_Value0 := lhs
			NUMBER1 := rhs[0]

			Elements_Value0.Child = NUMBER1
			Elements_Value0.LastChild = NUMBER1

			{
			}
			_ = NUMBER1
		case 21:
			Elements_Value0 := lhs
			STRING1 := rhs[0]

			Elements_Value0.Child = STRING1
			Elements_Value0.LastChild = STRING1

			{
			}
			_ = STRING1
		case 22:
			Members_Pair0 := lhs
			STRING1 := rhs[0]
			COLON2 := rhs[1]
			Array_Elements_Value3 := rhs[2]

			Members_Pair0.Child = STRING1
			STRING1.Next = COLON2
			COLON2.Next = Array_Elements_Value3
			Members_Pair0.LastChild = Array_Elements_Value3

			{
			}
			_ = STRING1
			_ = COLON2
			_ = Array_Elements_Value3
		case 23:
			Members_Pair0 := lhs
			STRING1 := rhs[0]
			COLON2 := rhs[1]
			Elements_Object_Value3 := rhs[2]

			Members_Pair0.Child = STRING1
			STRING1.Next = COLON2
			COLON2.Next = Elements_Object_Value3
			Members_Pair0.LastChild = Elements_Object_Value3

			{
			}
			_ = STRING1
			_ = COLON2
			_ = Elements_Object_Value3
		case 24:
			Members_Pair0 := lhs
			STRING1 := rhs[0]
			COLON2 := rhs[1]
			Elements_Value3 := rhs[2]

			Members_Pair0.Child = STRING1
			STRING1.Next = COLON2
			COLON2.Next = Elements_Value3
			Members_Pair0.LastChild = Elements_Value3

			{
			}
			_ = STRING1
			_ = COLON2
			_ = Elements_Value3
		}
		_ = ruleFlags
	}

	return &gopapageno.Grammar{
		NumTerminals:              numTerminals,
		NumNonterminals:           numNonTerminals,
		MaxRHSLength:              maxRHSLen,
		Rules:                     rules,
		CompressedRules:           compressedRules,
		PrecedenceMatrix:          precMatrix,
		BitPackedPrecedenceMatrix: bitPackedMatrix,
		MaxPrefixLength:           maxPrefixLength,
		Prefixes:                  prefixes,
		CompressedPrefixes:        compressedPrefixes,
		Func:                      fn,
		ParsingStrategy:           gopapageno.COPP,
	}
}
