package generator

import (
	"fmt"
	"os"
)

func emitFile(outdir string) (*os.File, error) {
	if _, err := os.Stat(outdir); !os.IsNotExist(err) {
		if err = os.Mkdir(outdir, os.ModeDir); err != nil {
			return nil, err
		}
	}

	fname := "parser.pg.go"
	file, err := os.Create(outdir + fname)
	if err != nil {
		return nil, err
	}

	fmt.Fprintf(file, "// Code generated by Gopapageno; DO NOT EDIT.\n")
	fmt.Fprintf(file, "package lexonorono\n\n")
	fmt.Fprintf(file, "import \"github.com/giornetta/gopapageno\"\n\n")

	return file, nil
}
