// Code generated by Gopapageno; DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/giornetta/gopapageno"
	"strings"
)

import (
	"math"
)

var parserInt64Pools []*gopapageno.Pool[int64]

// ParserPreallocMem initializes all the memory pools required by the semantic function of the parser.
func ParserPreallocMem(inputSize int, numThreads int) {
	parserInt64Pools = make([]*gopapageno.Pool[int64], numThreads)

	avgCharsPerNumber := float64(4)
	poolSizePerThread := int(math.Ceil((float64(inputSize) / avgCharsPerNumber) / float64(numThreads)))

	for i := 0; i < numThreads; i++ {
		parserInt64Pools[i] = gopapageno.NewPool[int64](poolSizePerThread)
	}
}

// Non-terminals
const (
	D_E_P_S_T = gopapageno.TokenEmpty + 1 + iota
	D_S_T
	NEW_AXIOM
	P_S
)

// Terminals
const (
	DIVIDE = gopapageno.TokenTerm + 1 + iota
	LPAR
	NUMBER
	PLUS
	RPAR
)

func SprintToken[TokenValue any](root *gopapageno.Token) string {
	var sprintRec func(t *gopapageno.Token, sb *strings.Builder, indent string)

	sprintRec = func(t *gopapageno.Token, sb *strings.Builder, indent string) {
		if t == nil {
			return
		}

		sb.WriteString(indent)
		if t.Next == nil {
			sb.WriteString("└── ")
			indent += "    "
		} else {
			sb.WriteString("├── ")
			indent += "|   "
		}

		switch t.Type {
		case D_E_P_S_T:
			sb.WriteString("D_E_P_S_T")
		case D_S_T:
			sb.WriteString("D_S_T")
		case NEW_AXIOM:
			sb.WriteString("NEW_AXIOM")
		case P_S:
			sb.WriteString("P_S")
		case gopapageno.TokenEmpty:
			sb.WriteString("Empty")
		case DIVIDE:
			sb.WriteString("DIVIDE")
		case LPAR:
			sb.WriteString("LPAR")
		case NUMBER:
			sb.WriteString("NUMBER")
		case PLUS:
			sb.WriteString("PLUS")
		case RPAR:
			sb.WriteString("RPAR")
		case gopapageno.TokenTerm:
			sb.WriteString("Term")
		default:
			sb.WriteString("Unknown")
		}
		if t.Value != nil {
			sb.WriteString(fmt.Sprintf(": %v", *t.Value.(*TokenValue)))
		}
		sb.WriteString("\n")

		sprintRec(t.Child, sb, indent)
		sprintRec(t.Next, sb, indent[:len(indent)-4])
	}

	var sb strings.Builder

	sprintRec(root, &sb, "")

	return sb.String()
}

func NewParser(opts ...gopapageno.ParserOpt) *gopapageno.Parser {
	numTerminals := uint16(6)
	numNonTerminals := uint16(5)

	maxRHSLen := 3
	rules := []gopapageno.Rule{
		{NEW_AXIOM, []gopapageno.TokenType{D_E_P_S_T}},
		{D_S_T, []gopapageno.TokenType{D_E_P_S_T, DIVIDE, D_E_P_S_T}},
		{P_S, []gopapageno.TokenType{D_E_P_S_T, PLUS, D_E_P_S_T}},
		{P_S, []gopapageno.TokenType{D_E_P_S_T, PLUS, D_S_T}},
		{NEW_AXIOM, []gopapageno.TokenType{D_S_T}},
		{D_S_T, []gopapageno.TokenType{D_S_T, DIVIDE, D_E_P_S_T}},
		{P_S, []gopapageno.TokenType{D_S_T, PLUS, D_E_P_S_T}},
		{P_S, []gopapageno.TokenType{D_S_T, PLUS, D_S_T}},
		{NEW_AXIOM, []gopapageno.TokenType{P_S}},
		{D_E_P_S_T, []gopapageno.TokenType{LPAR, D_E_P_S_T, RPAR}},
		{D_E_P_S_T, []gopapageno.TokenType{LPAR, D_S_T, RPAR}},
		{D_E_P_S_T, []gopapageno.TokenType{LPAR, P_S, RPAR}},
		{D_E_P_S_T, []gopapageno.TokenType{NUMBER}},
	}
	compressedRules := []uint16{0, 0, 5, 1, 13, 2, 41, 4, 69, 32770, 72, 32771, 105, 3, 0, 2, 32769, 20, 32772, 28, 0, 0, 1, 1, 25, 2, 1, 0, 0, 0, 2, 1, 35, 2, 38, 4, 2, 0, 4, 3, 0, 3, 4, 2, 32769, 48, 32772, 56, 0, 0, 1, 1, 53, 2, 5, 0, 0, 0, 2, 1, 63, 2, 66, 4, 6, 0, 4, 7, 0, 3, 8, 0, 0, 0, 3, 1, 81, 2, 89, 4, 97, 0, 0, 1, 32773, 86, 1, 9, 0, 0, 0, 1, 32773, 94, 1, 10, 0, 0, 0, 1, 32773, 102, 1, 11, 0, 1, 12, 0}

	maxPrefixLen := 4
	prefixes := [][]gopapageno.TokenType{
		{D_E_P_S_T, PLUS},
		{D_S_T, PLUS},
		{D_E_P_S_T, PLUS, D_E_P_S_T, PLUS},
		{D_E_P_S_T, PLUS, D_S_T, PLUS},
		{D_S_T, PLUS, D_E_P_S_T, PLUS},
		{D_S_T, PLUS, D_S_T, PLUS},
	}
	precMatrix := [][]gopapageno.Precedence{
		{gopapageno.PrecEquals, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEmpty},
		{gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecEmpty, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEquals},
		{gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEmpty, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes},
	}
	bitPackedMatrix := []uint64{
		12130059261139329364, 160,
	}

	fn := func(rule uint16, lhs *gopapageno.Token, rhs []*gopapageno.Token, thread int) {
		switch rule {
		case 0:
			NEW_AXIOM0 := lhs
			D_E_P_S_T1 := rhs[0]

			NEW_AXIOM0.Child = D_E_P_S_T1

			{
				NEW_AXIOM0.Value = D_E_P_S_T1.Value
			}
		case 1:
			D_S_T0 := lhs
			D_E_P_S_T1 := rhs[0]
			DIVIDE2 := rhs[1]
			D_E_P_S_T3 := rhs[2]

			D_S_T0.Child = D_E_P_S_T1
			D_E_P_S_T1.Next = DIVIDE2
			DIVIDE2.Next = D_E_P_S_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *D_E_P_S_T1.Value.(*int64) / *D_E_P_S_T3.Value.(*int64)
				D_S_T0.Value = newValue
			}
		case 2:
			P_S0 := lhs
			D_E_P_S_T1 := rhs[0]
			PLUS2 := rhs[1]
			D_E_P_S_T3 := rhs[2]

			P_S0.Child = D_E_P_S_T1
			D_E_P_S_T1.Next = PLUS2
			PLUS2.Next = D_E_P_S_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *D_E_P_S_T1.Value.(*int64) + *D_E_P_S_T3.Value.(*int64)
				P_S0.Value = newValue
			}
		case 3:
			P_S0 := lhs
			D_E_P_S_T1 := rhs[0]
			PLUS2 := rhs[1]
			D_S_T3 := rhs[2]

			P_S0.Child = D_E_P_S_T1
			D_E_P_S_T1.Next = PLUS2
			PLUS2.Next = D_S_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *D_E_P_S_T1.Value.(*int64) + *D_S_T3.Value.(*int64)
				P_S0.Value = newValue
			}
		case 4:
			NEW_AXIOM0 := lhs
			D_S_T1 := rhs[0]

			NEW_AXIOM0.Child = D_S_T1

			{
				NEW_AXIOM0.Value = D_S_T1.Value
			}
		case 5:
			D_S_T0 := lhs
			D_S_T1 := rhs[0]
			DIVIDE2 := rhs[1]
			D_E_P_S_T3 := rhs[2]

			D_S_T0.Child = D_S_T1
			D_S_T1.Next = DIVIDE2
			DIVIDE2.Next = D_E_P_S_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *D_S_T1.Value.(*int64) / *D_E_P_S_T3.Value.(*int64)
				D_S_T0.Value = newValue
			}
		case 6:
			P_S0 := lhs
			D_S_T1 := rhs[0]
			PLUS2 := rhs[1]
			D_E_P_S_T3 := rhs[2]

			P_S0.Child = D_S_T1
			D_S_T1.Next = PLUS2
			PLUS2.Next = D_E_P_S_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *D_S_T1.Value.(*int64) + *D_E_P_S_T3.Value.(*int64)
				P_S0.Value = newValue
			}
		case 7:
			P_S0 := lhs
			D_S_T1 := rhs[0]
			PLUS2 := rhs[1]
			D_S_T3 := rhs[2]

			P_S0.Child = D_S_T1
			D_S_T1.Next = PLUS2
			PLUS2.Next = D_S_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *D_S_T1.Value.(*int64) + *D_S_T3.Value.(*int64)
				P_S0.Value = newValue
			}
		case 8:
			NEW_AXIOM0 := lhs
			P_S1 := rhs[0]

			NEW_AXIOM0.Child = P_S1

			{
				NEW_AXIOM0.Value = P_S1.Value
			}
		case 9:
			D_E_P_S_T0 := lhs
			LPAR1 := rhs[0]
			D_E_P_S_T2 := rhs[1]
			RPAR3 := rhs[2]

			D_E_P_S_T0.Child = LPAR1
			LPAR1.Next = D_E_P_S_T2
			D_E_P_S_T2.Next = RPAR3

			{
				D_E_P_S_T0.Value = D_E_P_S_T2.Value
			}
		case 10:
			D_E_P_S_T0 := lhs
			LPAR1 := rhs[0]
			D_S_T2 := rhs[1]
			RPAR3 := rhs[2]

			D_E_P_S_T0.Child = LPAR1
			LPAR1.Next = D_S_T2
			D_S_T2.Next = RPAR3

			{
				D_E_P_S_T0.Value = D_S_T2.Value
			}
		case 11:
			D_E_P_S_T0 := lhs
			LPAR1 := rhs[0]
			P_S2 := rhs[1]
			RPAR3 := rhs[2]

			D_E_P_S_T0.Child = LPAR1
			LPAR1.Next = P_S2
			P_S2.Next = RPAR3

			{
				D_E_P_S_T0.Value = P_S2.Value
			}
		case 12:
			D_E_P_S_T0 := lhs
			NUMBER1 := rhs[0]

			D_E_P_S_T0.Child = NUMBER1

			{
				D_E_P_S_T0.Value = NUMBER1.Value
			}
		}
	}

	return gopapageno.NewParser(
		NewLexer(),
		numTerminals,
		numNonTerminals,
		maxRHSLen,
		rules,
		compressedRules,
		prefixes,
		maxPrefixLen,
		precMatrix,
		bitPackedMatrix,
		fn,
		gopapageno.COPP,
		opts...)
}
