version: '3'

vars:
  EXAMPLE: adder
  STRAT: opp
  FNAME: 'default'
  COUNT: 10

tasks:
  generate:
    cmds:
      - go run ./cmd/gopapageno/main.go -l ./examples/{{ .EXAMPLE }}/{{ .STRAT }}/{{ .EXAMPLE }}.l -g ./examples/{{ .EXAMPLE }}/{{ .STRAT }}/{{ .EXAMPLE }}.g -o ./examples/{{ .EXAMPLE }}/{{ .STRAT }}/ -s {{ .STRAT }} -log
    ignore_error: true

  run:
    cmds:
      - go run ./examples/{{ .EXAMPLE }}/{{ .STRAT }} -f ./examples/{{ .EXAMPLE }}/data/{{ .INPUTFILE }} -log

  generate-all-example:
    cmds:
      - for: [opp, aopp, copp]
        task: generate
        ignore_error: true
        vars:
            STRAT: '{{ .ITEM }}'
            EXAMPLE: '{{ .EXAMPLE }}'

  generate-all:
      cmds:
        - for: [adder, expr, json, xml]
          task: generate-all-example
          ignore_error: true
          vars:
            EXAMPLE: '{{ .ITEM }}'

  benchmark:
    cmds:
      - go test github.com/giornetta/gopapageno/examples/{{ .EXAMPLE }}/{{ .STRAT }} -bench=. -count={{ .COUNT }} -benchmem -timeout 2h -run=^$ > ./examples/{{ .EXAMPLE }}/benchmark_results/{{ .STRAT }}-{{ .FNAME }}.txt

  benchmark-all:
    cmds:
      - task: benchmark
        vars: { STRAT: 'opp'}
      - task: benchmark
        vars: { STRAT: 'aopp' }
      - task: benchmark
        vars: { STRAT: 'copp' }