// Code generated by Gopapageno; DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/giornetta/gopapageno"
	"strings"
)

import (
	"math"
)

var parserPools []*gopapageno.Pool[int64]

func ParserPreallocMem(inputSize int, numThreads int) {
	parserPools = make([]*gopapageno.Pool[int64], numThreads)

	avgCharsPerNumber := float64(2)
	poolSizePerThread := int(math.Ceil((float64(inputSize) / avgCharsPerNumber) / float64(numThreads)))

	for i := 0; i < numThreads; i++ {
		parserPools[i] = gopapageno.NewPool[int64](poolSizePerThread)
	}
}

// Non-terminals
const (
	S = gopapageno.TokenEmpty + 1 + iota
	T
)

// Terminals
const (
	LPAR = gopapageno.TokenTerm + 1 + iota
	NUMBER
	PLUS
	RPAR
)

func SprintToken[TokenValue any](root *gopapageno.Token) string {
	var sprintRec func(t *gopapageno.Token, sb *strings.Builder, indent string)

	sprintRec = func(t *gopapageno.Token, sb *strings.Builder, indent string) {
		if t == nil {
			return
		}

		sb.WriteString(indent)
		if t.Next == nil {
			sb.WriteString("└── ")
			indent += "    "
		} else {
			sb.WriteString("├── ")
			indent += "|   "
		}

		switch t.Type {
		case S:
			sb.WriteString("S")
		case T:
			sb.WriteString("T")
		case gopapageno.TokenEmpty:
			sb.WriteString("Empty")
		case LPAR:
			sb.WriteString("LPAR")
		case NUMBER:
			sb.WriteString("NUMBER")
		case PLUS:
			sb.WriteString("PLUS")
		case RPAR:
			sb.WriteString("RPAR")
		case gopapageno.TokenTerm:
			sb.WriteString("Term")
		default:
			sb.WriteString("Unknown")
		}
		if t.Value != nil {
			sb.WriteString(fmt.Sprintf(": %v", *t.Value.(*TokenValue)))
		}
		sb.WriteString("\n")

		sprintRec(t.Child, sb, indent)
		sprintRec(t.Next, sb, indent[:len(indent)-4])
	}

	var sb strings.Builder

	sprintRec(root, &sb, "")

	return sb.String()
}

func NewParser(opts ...gopapageno.ParserOpt) *gopapageno.Parser {
	numTerminals := uint16(5)
	numNonTerminals := uint16(3)

	maxRHSLen := 5
	rules := []gopapageno.Rule{
		{S, []gopapageno.TokenType{T}},
		{T, []gopapageno.TokenType{T, PLUS, T}},
		{T, []gopapageno.TokenType{T, PLUS, T, PLUS, T}},
		{T, []gopapageno.TokenType{LPAR, T, RPAR}},
		{T, []gopapageno.TokenType{NUMBER}},
	}
	compressedRules := []uint16{0, 0, 3, 2, 9, 32769, 32, 32770, 45, 1, 0, 1, 32771, 14, 0, 0, 1, 2, 19, 2, 1, 1, 32771, 24, 0, 0, 1, 2, 29, 2, 2, 0, 0, 0, 1, 2, 37, 0, 0, 1, 32772, 42, 2, 3, 0, 2, 4, 0}

	maxPrefixLen := 4
	prefixes := [][]gopapageno.TokenType{
		{T, PLUS},
		{T, PLUS, T, PLUS},
	}
	precMatrix := [][]gopapageno.Precedence{
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEquals},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEquals, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes},
	}
	bitPackedMatrix := []uint64{
		706460516440406,
	}

	fn := func(rule uint16, lhs *gopapageno.Token, rhs []*gopapageno.Token, thread int) {
		switch rule {
		case 0:
			S0 := lhs
			T1 := rhs[0]

			S0.Child = T1

			{
				S0.Value = T1.Value
			}
		case 1:
			T0 := lhs
			T1 := rhs[0]
			PLUS2 := rhs[1]
			T3 := rhs[2]

			T0.Child = T1
			T1.Next = PLUS2
			PLUS2.Next = T3

			{
				newValue := parserPools[thread].Get()
				*newValue = *T1.Value.(*int64) + *T3.Value.(*int64)
				T0.Value = newValue
			}
		case 2:
			T0 := lhs
			T1 := rhs[0]
			PLUS2 := rhs[1]
			T3 := rhs[2]
			PLUS4 := rhs[3]
			T5 := rhs[4]

			T0.Child = T1
			T1.Next = PLUS2
			PLUS2.Next = T3
			T3.Next = PLUS4
			PLUS4.Next = T5

			{
				newValue := parserPools[thread].Get()
				*newValue = *T1.Value.(*int64) + *T3.Value.(*int64)
				T0.Value = newValue
			}
		case 3:
			T0 := lhs
			LPAR1 := rhs[0]
			T2 := rhs[1]
			RPAR3 := rhs[2]

			T0.Child = LPAR1
			LPAR1.Next = T2
			T2.Next = RPAR3

			{
				T0.Value = T2.Value
			}
		case 4:
			T0 := lhs
			NUMBER1 := rhs[0]

			T0.Child = NUMBER1

			{
				T0.Value = NUMBER1.Value
			}
		}
	}

	return gopapageno.NewParser(
		NewLexer(),
		numTerminals,
		numNonTerminals,
		maxRHSLen,
		rules,
		compressedRules,
		prefixes,
		maxPrefixLen,
		precMatrix,
		bitPackedMatrix,
		fn,
		gopapageno.COPP,
		opts...)
}
