// Code generated by Gopapageno; DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/giornetta/gopapageno"
	"strings"
)

import (
	"math"
)

var parserPools []*gopapageno.Pool[int64]

func ParserPreallocMem(inputSize int, numThreads int) {
	parserPools = make([]*gopapageno.Pool[int64], numThreads)

	avgCharsPerNumber := float64(2)
	poolSizePerThread := int(math.Ceil((float64(inputSize) / avgCharsPerNumber) / float64(numThreads)))

	for i := 0; i < numThreads; i++ {
		parserPools[i] = gopapageno.NewPool[int64](poolSizePerThread)

	}
}

// Non-terminals
const (
	E = gopapageno.TokenEmpty + 1 + iota
	E_T
	S
)

// Terminals
const (
	LPAR = gopapageno.TokenTerm + 1 + iota
	NUMBER
	PLUS
	RPAR
)

func SprintToken[ValueType any](root *gopapageno.Token) string {
	var sprintRec func(t *gopapageno.Token, sb *strings.Builder, indent string)

	sprintRec = func(t *gopapageno.Token, sb *strings.Builder, indent string) {
		if t == nil {
			return
		}

		sb.WriteString(indent)
		if t.Next == nil {
			sb.WriteString("└── ")
			indent += "    "
		} else {
			sb.WriteString("├── ")
			indent += "|   "
		}

		switch t.Type {
		case E:
			sb.WriteString("E")
		case E_T:
			sb.WriteString("E_T")
		case S:
			sb.WriteString("S")
		case gopapageno.TokenEmpty:
			sb.WriteString("Empty")
		case LPAR:
			sb.WriteString("LPAR")
		case NUMBER:
			sb.WriteString("NUMBER")
		case PLUS:
			sb.WriteString("PLUS")
		case RPAR:
			sb.WriteString("RPAR")
		case gopapageno.TokenTerm:
			sb.WriteString("Term")
		default:
			sb.WriteString("Unknown")
		}

		if t.Value != nil {
			if v, ok := any(t.Value).(*ValueType); ok {
				sb.WriteString(fmt.Sprintf(": %v", *v))
			}
		}

		sb.WriteString("\n")

		sprintRec(t.Child, sb, indent)
		sprintRec(t.Next, sb, indent[:len(indent)-4])
	}

	var sb strings.Builder

	sprintRec(root, &sb, "")

	return sb.String()
}

func NewGrammar() *gopapageno.Grammar {
	numTerminals := uint16(5)
	numNonTerminals := uint16(4)

	maxRHSLen := 3
	rules := []gopapageno.Rule{
		{S, []gopapageno.TokenType{E}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E, PLUS, E_T}, gopapageno.RuleSimple},
		{S, []gopapageno.TokenType{E_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_T, PLUS, E_T}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{LPAR, E, RPAR}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{LPAR, E_T, RPAR}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{NUMBER}, gopapageno.RuleSimple},
	}
	compressedRules := []uint16{0, 0, 4, 1, 11, 2, 24, 32769, 37, 32770, 60, 3, 0, 1, 32771, 16, 0, 0, 1, 2, 21, 1, 1, 0, 3, 2, 1, 32771, 29, 0, 0, 1, 2, 34, 1, 3, 0, 0, 0, 2, 1, 44, 2, 52, 0, 0, 1, 32772, 49, 2, 4, 0, 0, 0, 1, 32772, 57, 2, 5, 0, 2, 6, 0}

	precMatrix := [][]gopapageno.Precedence{
		{gopapageno.PrecEquals, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEquals},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes},
	}
	bitPackedMatrix := []uint64{
		706597955393876,
	}

	fn := func(ruleDescription uint16, ruleFlags gopapageno.RuleFlags, lhs *gopapageno.Token, rhs []*gopapageno.Token, thread int) {
		switch ruleDescription {
		case 0:
			S0 := lhs
			E1 := rhs[0]

			S0.Child = E1
			S0.LastChild = E1

			{
				S0.Value = E1.Value
			}
			_ = E1
		case 1:
			E0 := lhs
			E1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E1
			E1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserPools[thread].Get()
				*newValue = *E1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E1
			_ = PLUS2
			_ = E_T3
		case 2:
			S0 := lhs
			E_T1 := rhs[0]

			S0.Child = E_T1
			S0.LastChild = E_T1

			{
				S0.Value = E_T1.Value
			}
			_ = E_T1
		case 3:
			E0 := lhs
			E_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E_T1
			E_T1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserPools[thread].Get()
				*newValue = *E_T1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_T1
			_ = PLUS2
			_ = E_T3
		case 4:
			E_T0 := lhs
			LPAR1 := rhs[0]
			E2 := rhs[1]
			RPAR3 := rhs[2]

			E_T0.Child = LPAR1
			LPAR1.Next = E2
			E2.Next = RPAR3
			E_T0.LastChild = RPAR3

			{
				E_T0.Value = E2.Value
			}
			_ = LPAR1
			_ = E2
			_ = RPAR3
		case 5:
			E_T0 := lhs
			LPAR1 := rhs[0]
			E_T2 := rhs[1]
			RPAR3 := rhs[2]

			E_T0.Child = LPAR1
			LPAR1.Next = E_T2
			E_T2.Next = RPAR3
			E_T0.LastChild = RPAR3

			{
				E_T0.Value = E_T2.Value
			}
			_ = LPAR1
			_ = E_T2
			_ = RPAR3
		case 6:
			E_T0 := lhs
			NUMBER1 := rhs[0]

			E_T0.Child = NUMBER1
			E_T0.LastChild = NUMBER1

			{
				E_T0.Value = NUMBER1.Value
			}
			_ = NUMBER1
		}
		_ = ruleFlags
	}

	return &gopapageno.Grammar{
		NumTerminals:              numTerminals,
		NumNonterminals:           numNonTerminals,
		MaxRHSLength:              maxRHSLen,
		Rules:                     rules,
		CompressedRules:           compressedRules,
		PrecedenceMatrix:          precMatrix,
		BitPackedPrecedenceMatrix: bitPackedMatrix,
		Func:                      fn,
		ParsingStrategy:           gopapageno.OPP,
		PreambleFunc:              ParserPreallocMem,
	}
}
